[package]
name = "dh"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
trust-dns-resolver = "0.23.2"
prettytable-rs = "^0.10"
